export const CHANGE_ADMIN_CONFIG = "CHANGE_ADMIN_CONFIG";
export const CHANGE_HOME_CURRENCY = "CHANGE_HOME_CURRENCY";
export const CHANGE_API_ACCESS_KEY = "CHANGE_API_ACCESS_KEY";
export const CHANGE_API_CURRENCIES = "CHANGE_API_CURRENCIES";
export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
export const UPDATE_EXCHANGE_RATES = "UPDATE_EXCHANGE_RATES";
export const UPDATE_EXCHANGE_RATES_FAILED = "UPDATE_EXCHANGE_RATES_FAILED";